#!/bin/sh

# After removal, delete the symbolic link in Wireshark's Global Plugins directory to out library.

set -e;

# Print tshark folders, find the entry for Global Plugins, get just the path, and trim leading and trailing whitespace
WS_PLUGIN_DIR="$(tshark -G folders | grep -i "^Global Plugins" | sed 's/^Global Plugins:[[:space:]]*//i')";
rm "$WS_PLUGIN_DIR/epan/mac_privacy.so";

#DEBHELPER#